### ISSUE TITLE
Where is model file? please commit it ! thanks!

### ISSUE THREAD

**Issue by XTL-666** [softwareTM/video_to_text_caption#2]
lstm model

**Comment by bakh-vv** [comment]
Sent #1

**Comment by XTL-666** [comment]
can you give me more test.avi videos



---Original---
From: "Bakhtiyar ***@***.***&gt;
Date: Tue, Nov 9, 2021 20:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bakh-vv/video_to_text_caption] Where is model file? pleasecommit it ! thanks! (Issue #2)




 
Closed #2.

**Comment by bakh-vv** [comment]
Yes, here it is https://drive.google.com/file/d/1GqpsN36RbUUqtmGiy2qj20_TFABB3JUg/view?usp=sharing
